name: Unity Build Android

#on:
#  push:
#    tags:
#      - 'v*'

on:
  pull_request:
    branches:
      - main

env:
  ARTIFACT_NAME: Lumisie
  BUILD_OUTPUT: build/android
  UNITY_VERSION: 6000.3.11f1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Cache Editor
        uses: actions/cache@v6
        id: cache-editor
        with:
          path: /home/runner/Unity/Hub/Editor/${{ env.UNITY_EDITOR_VERSION }}
          key: unity-editor-${{ env.UNITY_EDITOR_VERSION }}-${{ runner.os }}
      
      - name: Cache Library
        uses: actions/cache@v6
        with:
          path: $GITHUB_WORKSPACE/Library
          key: Library-Lumisie-TargetPlatform
          restore-keys: |
            Library-Lumisie-
            Library-
        
      - name: Install Unity Editor
        if: steps.cache-editor.outputs.cache-hit != 'true'
        run: |
          unity install "$UNITY_EDITOR_VERSION" -m android --yes --accept-eula
          unity editors -i
      - name: Activate license (Pro / serial)
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          mkdir -p ~/.local/share/unity3d/Unity
          echo "$UNITY_LICENSE" > ~/.local/share/unity3d/Unity/Unity_lic.ulf
          EDITOR_PATH=$(unity editors -i --format json | jq -r --arg v "$UNITY_EDITOR_VERSION" '.[] | select(.version==$v) | .path' | head -n1)
          EDITOR_PATH=$(unity editors -i --format json | jq -r --arg v "$UNITY_EDITOR_VERSION" '.data.[] | select(.version==$v) | .location' | head -n1)
          if [ -z "$EDITOR_PATH" ]; then
            EDITOR_PATH=$(find /opt /home -name Unity -type f 2>/dev/null | head -n1)
          fi
          echo "Using editor: $EDITOR_PATH"
          "$EDITOR_PATH" -batchmode -nographics -quit \
            -username "$UNITY_EMAIL" \
            -password "$UNITY_PASSWORD" \
            -logFile -
          
      - name: Build Android
        run: |
          unity build "$GITHUB_WORKSPACE" \
          --target Android \
          --execute-method Builder.AndroidBuild \
          --output-path ${{ env.BUILD_OUTPUT }}/${{ env.ARTIFACT_NAME }}

      - name: Upload Build Artifact
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ env.BUILD_OUTPUT }}/${{ env.ARTIFACT_NAME }}.apk
