name: Unity Build Android

on:
  push:
    tags:
      - v*

env:
  ARTIFACT_NAME: Lumisie
  BUILD_OUTPUT: build/android
  UNITY_VERSION: 6000.3.11f1
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Cache Library Restore
        uses: actions/cache/restore@v6
        with:
          path: Library
          key: Library-Lumisie
          restore-keys: |
            Library-

      - name: Build Android
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: Android
          buildName: ${{ env.ARTIFACT_NAME }}
          buildsPath: ${{ env.BUILD_OUTPUT }}
          cacheCheckpointInterval: 10

      - name: Upload Build Artifact
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ env.BUILD_OUTPUT }}/${{ env.ARTIFACT_NAME }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Library Save
        uses: actions/cache/save@v6
        if: always()
        with:
          path: Library
          key: Library-Lumisie